function show() 
{
    document.getElementById("content").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";
    document.getElementById("customerimg1").style.opacity=0.7;
   
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;
    
    document.getElementById("customerimg1").style.borderColor="#ff4800";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";

    
     


}
function show2()
{
    document.getElementById("content2").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";

    
    document.getElementById("customerimg2").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="#ff4800";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";


}
function show3()
{
    document.getElementById("content3").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg3").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="#ff4800";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
}
function show4()
{
    document.getElementById("content4").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg4").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="#ff4800";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
}
function show5()
{
    document.getElementById("content5").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg5").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="#ff4800";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
}
function show6()
{
    document.getElementById("content6").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg6").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="#ff4800";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
}
function show7()
{
    document.getElementById("content7").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg7").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

 document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="#ff4800";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
}
function show8()
{
    document.getElementById("content8").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content9").style.display="none";

    document.getElementById("customerimg8").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;

    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="#ff4800";
    document.getElementById("customerimg9").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
}
function show9()
{
    document.getElementById("content9").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("customerimg9").style.opacity=0.7;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;
    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg9").style.borderColor="#ff4800";
    document.getElementById("customerimg8").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    
    
}
function show10()
{
    document.getElementById("content10").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content9").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("customerimg10").style.opacity=0.7;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="#ff4800";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    
}
function show11()
{
    document.getElementById("content11").style.display="inline-block";
    document.getElementById("content10").style.display="none";
    document.getElementById("content12").style.display="none";
    document.getElementById("content9").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("customerimg11").style.opacity=0.7;
    document.getElementById("customerimg10").style.opacity=1;
    document.getElementById("customerimg12").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg11").style.borderColor="#ff4800";
    document.getElementById("customerimg10").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    
}
function show12()
{
    document.getElementById("content12").style.display="inline-block";
    document.getElementById("content11").style.display="none";
    document.getElementById("content10").style.display="none";
    document.getElementById("content9").style.display="none";
    document.getElementById("content").style.display="none";
    document.getElementById("content2").style.display="none";
    document.getElementById("content4").style.display="none";
    document.getElementById("content3").style.display="none";
    document.getElementById("content5").style.display="none";
    document.getElementById("content6").style.display="none";
    document.getElementById("content7").style.display="none";
    document.getElementById("content8").style.display="none";
    document.getElementById("customerimg12").style.opacity=0.7;
    document.getElementById("customerimg11").style.opacity=1;
    document.getElementById("customerimg10").style.opacity=1;
    document.getElementById("customerimg9").style.opacity=1;
    document.getElementById("customerimg1").style.opacity=1;
    document.getElementById("customerimg3").style.opacity=1;
    document.getElementById("customerimg4").style.opacity=1;
    document.getElementById("customerimg5").style.opacity=1;
    document.getElementById("customerimg6").style.opacity=1;
    document.getElementById("customerimg7").style.opacity=1;
    document.getElementById("customerimg2").style.opacity=1;
    document.getElementById("customerimg8").style.opacity=1;
    document.getElementById("customerimg1").style.borderColor="white";
    document.getElementById("customerimg2").style.borderColor="white";
    document.getElementById("customerimg3").style.borderColor="white";
    document.getElementById("customerimg4").style.borderColor="white";
    document.getElementById("customerimg5").style.borderColor="white";
    document.getElementById("customerimg6").style.borderColor="white";
    document.getElementById("customerimg7").style.borderColor="white";
    document.getElementById("customerimg12").style.borderColor="#ff4800";
    document.getElementById("customerimg11").style.borderColor="white";
    document.getElementById("customerimg10").style.borderColor="white";
    document.getElementById("customerimg8").style.borderColor="white";
    
}



